### ISSUE TITLE
Hidden pdraw dependency in SDKCore's interface

### ISSUE THREAD

**Issue by Dan-Cape** [Parrot-Developers/groundsdk-ios#2]
According to the headers, `SdkCoreFrame` has a `pdrawFrame` property, which is a `void*`, with comments saying it's a `struct pdraw_video_frame*`. The struct carries some info about the data layout, such as image dimensions and image format -- it's necessary to really use `SdkCoreFrame`.

Since SDKCore's pdraw dependency is hidden behind a `void*`, none of the pdraw headers describing `pdrawFrame` make it into the iOS framework (see: pod_sdkcore).

We're working around this issue by adding the necessary pdraw headers (and headers from the child dependency `video_metadata`) to the prebuilt SDKCore.Framework. It works fine, but we'd rather find a more permanent solution if possible.

**Comment by jeromegournay** [comment]
https://forum.developer.parrot.com/t/hidden-pdraw-dependency-in-sdkcores-interface/9336
